### ISSUE TITLE
bit of a headsup(v1.16.5)

### ISSUE THREAD

**Issue by SpinnyBoiii** [Xtreme533/Forging-Beyond#1]
![image](https://user-images.githubusercontent.com/49210394/123875484-0fb85000-d93a-11eb-88d2-52ab4ffc9302.png)
![image](https://user-images.githubusercontent.com/49210394/123875493-12b34080-d93a-11eb-93ae-a8a3d0d0d50e.png)
Might want to edit the config file for the max allowed value to not have a comma, I initially copypasted it since i wanted to get as close to no cap as possible but that just rounds the cap to 32 or 33

**Comment by astralship-system** [comment]
Guess that's another spelling mistake to tidy up...
Will be fixed in next version.

**Comment by astralship-system** [comment]
Fixed in 0.0.2, See [the tags page](https://github.com/Xtreme533/Forging-Beyond/tags) or [the CurseForge page.](https://www.curseforge.com/minecraft/mc-mods/forging-beyond/files/all)
