### ISSUE TITLE
Bit of an issue in the config

### ISSUE THREAD

**Issue by SpinnyBoiii** [Xtreme533/Forging-Beyond#2]
![image](https://user-images.githubusercontent.com/49210394/129797589-0e72a336-4882-4606-9c41-444297145353.png)
tried with a dot, a comma and just the number, but the cap doesn't seem to work

**Comment by astralship-system** [comment]
What do you mean exactly by the cap not working?

**Comment by SpinnyBoiii** [comment]
xp-level-limit=32767
xp-level-limit=32,767
xp-level-limit=32.767
It defaults back to 40 in any of these cases on minecraft version 1.16.5, so I'd guess the cap is either lower than the number said or it's an issue with numbers in the thousands?

**Comment by astralship-system** [comment]
Does this happen on a singleplayer world? The mod will default to 40 if the server you play on doesn't have the mod installed.

**Comment by SpinnyBoiii** [comment]
that's the thing, i was doing this in a singleplayer world

**Comment by astralship-system** [comment]
I see the issue, will be fixed in 0.0.3.
